# инструкция запуска docker образа (т.е. вместо команды docker run....)
version: '3.7'

services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '80:8000'
    restart: always

    volumes:
      - volume-python6:/app/storage
volumes:
  volume-python6:
    external: true

#volumes:
#  db-data:
#    external: true

# docker-compose up -d --build
# docker-compose down
